apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: 512378127667.dkr.ecr.ca-central-1.amazonaws.com/eks-platform-app:3443a4e3e1d01fdbb7f8d0180e75effb4c1006b1
          ports:
            - containerPort: 8080
