apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: 512378127667.dkr.ecr.ca-central-1.amazonaws.com/eks-platform-app:7f91cd37820d17b1f50b6ae84e1c4dae2e462330
          ports:
            - containerPort: 8080