server:
  persistentVolume:
    enabled: false

  service:
    type: ClusterIP

  retention: "6h"

alertmanager:
  persistence:
    enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: false