provider:
  name: aws

policy: upsert-only

registry: txt
txtOwnerId: eks-platform

sources:
  - ingress

domainFilters:
  - tm.paramjyot2ray.com
  
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::512378127667:role/external-dns