name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type destroy to confirm full platform and infrastructure destruction"
        required: true
        type: string

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
  TF_WORKING_DIR: terraform

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    if: github.event.inputs.confirm_destroy == 'destroy'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}

      - name: Update kubeconfig
        continue-on-error: true
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      - name: Delete ArgoCD applications
        continue-on-error: true
        run: |
          kubectl delete -f kubernetes/argocd/ --ignore-not-found=true

      - name: Delete application resources
        continue-on-error: true
        run: |
          kubectl delete -f kubernetes/app/ --ignore-not-found=true
          kubectl delete -f kubernetes/backend/ --ignore-not-found=true
          kubectl delete -f kubernetes/cert-manager/ --ignore-not-found=true

      - name: Delete platform namespaces
        continue-on-error: true
        run: |
          kubectl delete namespace monitoring --ignore-not-found=true --wait=false
          kubectl delete namespace external-dns --ignore-not-found=true --wait=false
          kubectl delete namespace traefik --ignore-not-found=true --wait=false
          kubectl delete namespace cert-manager --ignore-not-found=true --wait=false
          kubectl delete namespace argocd --ignore-not-found=true --wait=false

      - name: Wait for AWS load balancers to delete
        run: sleep 180

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve